services:
  auth-proxy:
    restart: unless-stopped
    image: docker pull ghcr.io/hackerspacekrk/auth-proxy:latest
    ports:
      - "8456:80"
    environment:
      - AUTHENTIK_TOKEN_FILE=/var/run/secrets/authentik_token
